orders/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("menu/", views.index, name="menu"),
    path("checkout/" , views.checkout, name="checkout")
]

pinocchios/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("users.urls")),
    path("", include("orders.urls")),
    path("admin/", admin.site.urls),
]

users/urls.py
from django.urls import path

from . import views

# users urls
urlpatterns = [
    path("", views.index_user, name="index_user"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register_view, name="register"),
    path("user", views.user_home, name="user_home")

]

orders/models.py
from django.db import models

# Create your models here.
class Categories(models.Model):
    category_name = models.CharField(max_length=30)

    def __str__(self):
        return self.category_name

class Options(models.Model):
    option_name = models.CharField(max_length=30)

    def __str__(self):
        return self.option_name

class Menu(models.Model):
    category_id = models.ForeignKey(Categories, on_delete=models.CASCADE, related_name="category")
    menu_item = models.CharField(max_length=30)
    menu_options = models.ForeignKey(Options,models.SET_NULL,blank=True,null=True)

    def __str__(self):
        return self.menu_item

class Topping(models.Model):
    topping_name = models.CharField(max_length=30)
    option_type = models.ForeignKey(Options,models.SET_NULL,blank=True,null=True)

    def __str__(self):
        return self.topping_name

class Prices(models.Model):
    ITEM_SIZES = (
        ('S', 'Small'),
        ('L', 'Large'),
    )
    menu_id = models.ForeignKey(Menu, on_delete=models.CASCADE)
    item_size = models.CharField(max_length=1, choices=ITEM_SIZES)
    item_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.menu_id} {self.item_size} {self.item_price}"

class Orders(models.Model):
    ORDER_STATUS = (
        ('P', 'Pending'),
        ('C', 'Completed'),
    )
    user_id = models.IntegerField()
    item_number = models.ForeignKey(Prices, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    order_details = models.CharField(max_length=250,blank=True)
    order_date = models.DateField()
    order_status = models.CharField(max_length=1, choices=ORDER_STATUS,default="P")

users/models.py
from django.db import models

# Create your models here.

orders/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.models import User

from .models import Categories,Options,Menu,Topping,Prices,Orders

# Orders Views
def index(request):

    if request.method == "POST":
        return render(request, "orders/checkout.html")

    else:
        #build data array
        pin_category = Categories.objects.all()
        pin_foods = Menu.objects.all()
        pin_prices = Prices.objects.all()
        pin_topping = Topping.objects.all()

        food_items = {}

        for cg in pin_category:
        	food_items[cg.category_name] = []
        	query_menu = pin_foods.filter(category_id = cg.id)
        	for fd in query_menu:
        		menu_to_qs = {}
        		query_topping = pin_topping.filter(option_type_id = fd.menu_options_id)
        		query_prices = pin_prices.filter(menu_id = fd.id)
        		opt_dict = {'toppings': query_topping, 'prices': query_prices}
        		menu_to_qs[fd.menu_item] = opt_dict
        		food_items[cg.category_name].append(menu_to_qs)

    context = {
        "data": food_items
    }
    return render(request, "orders/index.html", context)

def checkout(request):
    current_user = request.user
    orderdetails = Orders.objects.filter(user_id = current_user.id)

    context = {
        "myorders": orderdetails
    }

    if request.method == "POST":
        orderdetails.filter(order_status = 'P').update(order_status = 'C')
        return render(request, "users/user.html",context)
    else:
        orderdetails.filter(order_status = 'P')


    return render(request, "orders/checkout.html",context)

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from orders.models import Orders

# users views

def index_user(request):
    if not request.user.is_authenticated:
        return render(request, "users/login.html", {"message": None})
    context = {
        "user": request.user
    }
    return render(request, "users/user.html", context)

def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        #authenticate user
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index_user"))
        else:
            return render(request, "users/error.html", {"message": "Invalid credentials.", "backto": "login"})
    else:
        return render(request, "users/login.html", {"message": None})

def register_view(request):
    if request.method == "POST":
        u_firstname = request.POST.get('firstname')
        u_lastname = request.POST.get('lastname')
        u_email = request.POST.get('email')
        u_uname = request.POST.get('username')
        u_pwd = request.POST.get('password')

        #check if user exists
        userlist = User.objects.all()
        namecheck = userlist.filter(username = u_uname)
        emailcheck = userlist.filter(email = u_email)

        if namecheck:
            return render(request, "users/error.html", {"message": "Username already exists!", "backto": "register"})
        elif emailcheck:
            return render(request, "users/error.html", {"message": "Email already exists!", "backto": "register"})
        else:
            newuser = User.objects.create_user(u_uname, u_email, u_pwd)
            newuser.first_name = u_firstname
            newuser.last_name = u_lastname
            newuser.save()
            return render(request, "users/login.html")
    else:
        return render(request, "users/register.html")


def logout_view(request):
    logout(request)
    return render(request, "users/login.html")

def user_home(request):
    current_user = request.user
    print(current_user.is_superuser)

    #admin show all
    if current_user.is_superuser:
        orderdetails = Orders.objects.all()
    else:
        orderdetails = Orders.objects.filter(user_id = current_user.id)

    context = {
        "myorders": orderdetails
    }
    return render(request, "users/user.html",context)

orders/templates/orders/checkout.html
{% extends "base.html" %}

{% block title %}
    Home
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="display-3 text-center">Hello, {{ user.first_name }}</h1>
            <h4 class="text-center">Complete your Order</h4>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">OrderID</th>
                  <th scope="col">Item</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Amount</th>
                  <th scope="col">Date</th>
                  <th scope="col">Details</th>
                </tr>
              </thead>
                  <tbody>
                      {% for od in myorders %}
                    <tr>
                      <td>{{ od.id }}</td>
                      <td>{{ od.item_number.menu_id }}</td>
                      <td>{{ od.quantity }}</td>
                      <td>{{ od.item_number.item_price }}</td>
                      <td>{{ od.order_date }}</td>
                      <td>{{ od.details }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
            </table>
            <form action"user/" method"POST">
            <button type="submit" class="btn btn-success">Complete</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

orders/templates/orders/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Orders{% endblock %}

{% block additional_css %}
<link rel="stylesheet" type="text/css" href="{% static 'orders/styles.css' %}">
{% endblock additional_css %}

{% block additional_js %}
<script src="{% static 'orders/menuorders.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock additional_js %}
{% block body %}

<div class="container">
  <div class="row">
    <div class="col-sm-9">


  <h1 class="ita_header display-3 text-center">Menu</h1>

{% for category, foods in data.items %}
<div class="row">
  <div class="col-sm-12">
  <h3 class="menu_category">{{category}}</h1>

  <div class="row">
    {% for opt in foods %}
      {% for k, v in opt.items %}
          <div class="col-sm-4">
          <!-- Modal Button -->
              <button class="btn btn-outline-success btn-block" type="button" data-toggle="modal" data-target="#{{ k|lower|slugify }}">
                {{ k }}
              </button>

          </div>

          <!-- Modal -->
          <div class="modal fade" id="{{ k|lower|slugify }}" tabindex="-1" role="dialog" aria-labelledby="{{ k|lower|slugify }}-ModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h3 class="modal-title" id="{{ k|lower|slugify }}-ModalLabel">{{ k }}</h3>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

                <div class="modal-body text-center">
                  <h4>Quantity</h4>
                  <div class="row justify-content-md-center">
                    <div class="col-md-3">
                      <input class="input-quantity form-control" type="number" name="quantity" min="1" value="0">
                    </div>
                  </div>
                </div>

                <div class="modal-body text-center">
                  <div class="row">

                    {% for tp in v.toppings.all  %}
                    <div class="col-sm-6">
                    <div class="form-check text-left">
                      <input class="input-toppings form-check-input" type="checkbox" id="{{ k|lower|slugify}}-{{tp.id}}" value="{{tp.id}}">
                      <label class="form-check-label" for="inlineCheckbox1"><span>{{ tp.topping_name }}</span></label>
                    </div>
                    </div>
                    {% endfor %}

                  </div>
                </div>

                <div class="modal-body text-center">
                    {% for pr in v.prices.all  %}
                    <div class="form-check form-check-inline">
                      <label class="form-check-label">
                        <input class="input-price form-check-input" type="radio" name="inlineRadioOptions" id="{{ pr.id }}" value="{{ pr.item_price }}">
                        <span>{{ pr.get_item_size_display }}: ${{ pr.item_price }}</span>
                      </label>
                    </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                  <button type="button" class="add-to-cart btn btn-primary">Add to Cart</button>
                </div>
              </div>
            </div>
          </div>

        {% endfor %}
     {% endfor %}

  </div>

</div>
</div>
 {% endfor %}

    </div> <!-- menu -->

    <div class="checkout-cart col-sm-3">
      <div class="row">
        <div class="col-sm-12">
          <h1 class=" text-center menu_category">Cart</h1>
          <hr>
          <h3>Order Total: &#x24;<span id="total-order-cost">0</span></h3>

          <form id="final-checkout" action="{% url 'checkout' %}" method="POST">
            {% csrf_token %}
              <div id="order-list" class="form-group">
                <button type="submit" id="btn-place-order" type="button" class="btn btn-block btn-success">Checkout</button>
              </div>
          </form>

        </div>
      </div>
    </div>


  </div> <!-- main-row -->
</div> <!-- container -->

{% endblock %}

users/templates/users/error.html
{% extends "base.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
<div class="container text-center">
  <div class="row align-items-center">
    <div class="col"></div>
    <div class="col-sm-4">
      <div class="alert alert-danger" role="alert">{{ message }}</div>
    </div>
    <div class="col"></div>
  </div>
  <div class="row align-items-center">
    <div class="col"></div>
    <div class="col-sm-4">
      <div><a href="/{{backto}}">Back to {{ backto|capfirst }} </a></div>
    </div>
    <div class="col"></div>
  </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}

{% block title %}
    User Login
{% endblock %}

{% block body %}
{% if user.is_authenticated %}
<div class="container text-center">
  <div class="row align-items-center">
    <div class="col"></div>
    <div class="col-sm-4">
      <div class="alert alert-primary" role="alert">Already Logged In!</div>
    </div>
    <div class="col"></div>
  </div>
</div>
{% else %}
<div class="container text-center">
  <div class="row align-items-center">
    <div class="col"></div>
    <div class="col-sm-4">

      <h2 class="ita_header display-3">LOG IN</h2>
      <form action="{% url 'login' %}" method="POST">
          {% csrf_token %}
        <div class="form-group">
          <label for="username"></label>
          <input type="username" class="form-control" name="username" autocomplete="off" placeholder="Username">
          <label for="password"></label>
          <input type="password" class="form-control" name="password" autocomplete="off" placeholder="Password">
          <br>
          <button type="submit" class="btn btn-outline-secondary btn-lg">Log In</button>
        </div>
      </form>
    </div>
    <div class="col"></div>
  </div>
</div>
{% endif %}
{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}

{% block title %}
    User Registration
{% endblock %}

{% block body %}
{% if user.is_authenticated %}
<div class="container text-center">
  <div class="row align-items-center">
    <div class="col"></div>
    <div class="col-sm-4">
      <div class="alert alert-primary" role="alert">Already Logged In!</div>
    </div>
    <div class="col"></div>
  </div>
</div>
{% else %}
<div class="container text-center">
  <div class="row align-items-center">
    <div class="col"></div>
    <div class="col-sm-4">
      <h2 class="display-3 ita_header">Register</h2>
      <form action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="firstname"></label>
          <input type="text" class="form-control" name="firstname" autocomplete="off" placeholder="First Name" required>
          <label for="lastname"></label>
          <input type="text" class="form-control" name="lastname" autocomplete="off" placeholder="Last Name" required>
          <label for="user-email"></label>
          <input type="email" class="form-control" name="email" autocomplete="off" placeholder="Email" required>

          <label for="username"></label>
          <input type="username" class="form-control" name="username" autocomplete="off" placeholder="Username" required>
          <label for="password"></label>
          <input type="password" class="form-control" name="password" autocomplete="off" placeholder="Password" required>
          <br>
          <button type="submit" class="btn btn-outline-secondary btn-lg">Register</button>
        </div>
      </form>
    </div>
    <div class="col"></div>
  </div>
</div>
{% endif %}
{% endblock %}

users/templates/users/user.html
{% extends "base.html" %}

{% block title %}
    Home
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h1 class="display-3">Hello, {{ user.first_name }}</h1>
            <h4>Your Order History</h4>
            <table class="table table-responsive">
              <thead>
                <tr>
                  <th scope="col">OrderID</th>
                  <th scope="col">Item</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Amount</th>
                  <th scope="col">Date</th>
                  <th scope="col">Details</th>
                </tr>
              </thead>
                  <tbody>
                      {% for od in myorders %}
                    <tr>
                      <td>{{ od.id }}</td>
                      <td>{{ od.item_number.menu_id }}</td>
                      <td>{{ od.quantity }}</td>
                      <td>{{ od.item_number.item_price }}</td>
                      <td>{{ od.order_date }}</td>
                      <td>{{ od.details }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
            </table>
        </div>
        <div class="col-sm-6">
            <h1 class="display-3">About Us</h1>
            <p>Noch's has reached a landmark this year......<strong>50 years in business!</strong> We've been feeding Harvard and the surrounding area
            <strong><u>since 1966!</u></strong>
            We sell award-winning sicilian-style pizza and mouth-watering steak subs! We have over 500 reviews on
            <strong><a href="https://www.yelp.com/biz/pinocchios-pizza-and-subs-cambridge" title="Yelp">Yelp</a></strong>
            --- check it out! Pinocchio's was recently named 1st Runner-up in the 'Boston's Best Pizza Poll'
            conducted by Eater.com and Top College Pizza Shop by Thrillist.com.
            </p>
            <h1 class="display-3">Contact Us</h1>
            <ul>
                <li>74 Winthrop Street</li>
                <li>Harvard Square</li>
                <li>617-876-4897</li>
                <li>pinocchiospizza1@gmail.com</li>
                <li>Twitter @PinocchiosPizz</li>
                <li>Instagram @pinocchiospizza1</li>
            </ul>
        </div>
    </div>
</div>

{% endblock %}